### ISSUE TITLE
Implement verification credential revocation

### ISSUE THREAD

**Issue by Vishwas1** [hypersign-protocol/hid-node#117]
- https://hyperledger-indy.readthedocs.io/projects/hipe/en/latest/text/0011-cred-revocation/README.html
- https://github.com/uport-project/revocation-registry
- https://tykn.tech/identity-revocation-blockchain/

**Comment by Vishwas1** [comment]
- A role a system might perform by mediating the creation and verification of identifiers, keys, and other relevant data, such as verifiable credential schemas, **revocation registries**, issuer public keys, and so on, which might be required to use verifiable credentials.
- Revocation by the issuer should not reveal any identifying information about the subject, the holder, the specific verifiable credential, or the verifier.
- Issuers can disclose the **revocation** reason.

**Comment by Vishwas1** [comment]
- https://www.w3.org/TR/vc-data-model/#status
- https://w3c-ccg.github.io/vc-extension-registry/
- https://w3c-ccg.github.io/vc-csl2017/
- https://w3c-ccg.github.io/vc-csl2017/#introduction

**Comment by arnabghose997** [comment]
Closing this issue as it is addressed in https://github.com/hypersign-protocol/hid-node/issues/151
