### ISSUE TITLE
Test suites for did by w3c 

### ISSUE THREAD

**Issue by Vishwas1** [hypersign-protocol/hid-node#149]
- [x] First go through this [test suite spec](https://w3c.github.io/did-test-suite/)
- [x] Then run [this ](https://github.com/hypersign-protocol/did-test-suite)project to test our did
- [ ] Also take a look at the test server https://github.com/hypersign-protocol/did-test-suite/tree/main/packages/did-core-test-server

**Comment by arnabghose997** [comment]
https://docs.cheqd.io/identity/architecture/dids/w3c-did-test-suite
