### ISSUE TITLE
Research on adding test framework in hid-node ssi module

### ISSUE THREAD

**Issue by Vishwas1** [hypersign-protocol/hid-node#169]
- [ ] Implement a basic framework. Like there should a test folder where all test case are present. Upon running a `test` command , it should execute all the test cases.

**Comment by arnabghose997** [comment]
Unit test for Tx based RPC's have been added:

- Create DID: https://github.com/hypersign-protocol/hid-node/issues/171
- Update DID: https://github.com/hypersign-protocol/hid-node/issues/172
- Deactivate DID: https://github.com/hypersign-protocol/hid-node/issues/173
- Create Schema: https://github.com/hypersign-protocol/hid-node/issues/174
- Register Credential Status: https://github.com/hypersign-protocol/hid-node/issues/175

**Comment by arnabghose997** [comment]
Unit tests (Success Scenarios) for Query based RPC's have been added:

- https://github.com/hypersign-protocol/hid-node/issues/192
