### ISSUE TITLE
Proper format for `method-specific-id` of DID Identifier

### ISSUE THREAD

**Issue by Vishwas1** [hypersign-protocol/hid-node#206]
What is the right UUId we should use for out DID. The current UUID is generated using npm package `uuid` in the hypersign-ss-sdk. Is this the right way to do that?  

This way any insecure DID can also be registered on our network  and that will have security issues. For example any one can create a DID (since its getting created outside the node) like `did:hid:<some random text>`  and it will get registered on the network.  Our network will accept this did since it might be unique across. But this might have issue. The network does not know if this uuid was generated properly or not. So whats the point of having a network with random data? since the network can not guarantee that its secure. 

Some thoughts:

1. While creating DID, would it be better that the hid-node assigns a new identifier instead of taking identifier from SDK? 
2. If we agrees on point 1, then we have two ways to do that.
    - We either use some package in Go-lang to generate UUID.
    - Or, we use wallet address as part of did like this `did:hid:<walllet>`. I mean we can simply use same package (by comsos) which is used to generated wallet address (I believe that is more audited)

Also do check what and how cheqd guys are doing...

**Comment by Vishwas1** [comment]
See example of SOL DID

**Comment by Vishwas1** [comment]
- [ ] what is the regex to verify hid wallet address (except the hid)

**Comment by arnabghose997** [comment]
This PR intends to check for DID ID in `did:hs:<multibase-public-key>` format

**Comment by Vishwas1** [comment]
https://hackmd.io/@icZC4epNSnqBbYE0hJYseA/S1eUS2BQw#Creation 

![image](https://user-images.githubusercontent.com/15328561/176353273-47b829b5-c826-4e48-aa69-e98ef7022f09.png)
