### ISSUE TITLE
Implement namespace for DID

### ISSUE THREAD

**Issue by Vishwas1** [hypersign-protocol/hid-node#217]
- [x] Figure out a way to add a new variable in configuration file. 

```
// config.toml

## ssi related configs
did-method='hid'
namespace='mainnet'
```
- [x] Research  on what Indy and others are doing
- [x]  Implement the format of namespace; it could follow these rules

1. It is Optional; if not passed, then by default its`mainnet` 
2. It should contain chars (a-z, A-Z, 0-9) and `-` 
3. It Should not contain spaces
4. It should have max char 10

**Comment by arnabghose997** [comment]
> Figure out a way to add a new variable in configuration file.

The namespace variable can be passed through genesis.json
