### ISSUE TITLE
Update the credential status document

### ISSUE THREAD

**Issue by Vishwas1** [hypersign-protocol/hid-node#218]
In this doc https://github.com/hypersign-protocol/hid-node/blob/main/docs/ssi/cred-ops.md add the following information 

- [x] Add the reference link of the spec which you followed to come up with the st. of credential status and proof. - This always do any doc, like give the link of the spec which it conforms. 
- [x] Add what all possible `currentStatus` are.  like `Live` is one, what else?
- [x] (Cli)[https://github.com/hypersign-protocol/hid-node/blob/main/docs/ssi/cred-ops.md#cli] is nnot really cli, call this heading -`Query Credential Status`

**Comment by arnabghose997** [comment]
All supported values of Credential Status has been added in this PR: https://github.com/hypersign-protocol/hid-node/issues/219

**Comment by arnabghose997** [comment]
> Add the reference link of the spec which you followed to come up with the st. of credential status and proof. - This always do any doc, like give the link of the spec which it conforms.

Updated here: https://github.com/hypersign-protocol/hid-node/blob/340eaa3520782a6bd6520c9408f3e54f68dfcd67/x/ssi/keeper/msg_server_credential.go#L15

> (Cli)[https://github.com/hypersign-protocol/hid-node/blob/main/docs/ssi/cred-ops.md#cli] is nnot really cli, call this heading -Query Credential Status

Updated here: https://github.com/hypersign-protocol/hid-node/blob/main/docs/ssi/cred-ops.md#querying-credential-status
