### ISSUE TITLE
Use `@` in `@context` DID doc structure

### ISSUE THREAD

**Issue by Vishwas1** [hypersign-protocol/hid-node#22]
- `@context` is mandatory in DID doc structure. The DID Doc is in  [JSON-ld](https://github.com/Vishwas1/ss/blob/main/linked-data-and-json-ld.md) format  which other systems understand.  If we mess with this st, the other system would not recognize our did-doc. 

Now, there is concept of [Aliasing Keywords](https://json-ld.org/spec/latest/json-ld/#aliasing-keywords) in json-ld spec by web3 but it is not for `@context`. we can have alias for other fields like `@type -> type`, `@id -> id` though but not for `@context`.

I have noticed people have work around to this problem in go lang. 
- https://github.com/piprate/json-gold
- https://golangexample.com/simple-json-ld-in-go/

**Comment by arnabghose997** [comment]
Need to check on the implementation later

**Comment by arnabghose997** [comment]
Discussion of support for Protobuf for fields like @context: https://github.com/w3c/vc-data-model/issues/642

**Comment by Vishwas1** [comment]
**Arnab | Hypersign — Today at 10:08**
The discussion there is pretty language heavy. So couldn't understand at first read

**hermit | Hypersign — Today at 10:09**
The expectation is that if someone wants to do this with protobuf, then they would define a fairly lightweight specification and tell folks how to convert a VC to/from protobuf. One rule that spec would have in it is how to convert from @context to _at_context or whatever you feel would be appropriate.

**hermit | Hypersign — Today at 10:10**
all it is saying is,  there is no action taken on this sissue.  if we have to use protobuf then we need to  add serialization and deserialization spec (for ourselves)
like converting @context =>  _context / at_context  and back to @context 
we will do this only

**Arnab | Hypersign — Today at 10:12**
Okay, conversion from _at_context to @context will happen on the sdk side, I assume

**hermit | Hypersign — Today at 10:13**
the clent witll send @context in did doc =>  the node will first convert @context to at_context and then parse it via protobuf
it should happen at node side becuase tomorrow we may use someone else sDK  (like HL-aries)

**Comment by arnabghose997** [comment]
Closing this issue, as current implementation with `context` for storing on the network is fine. But soon, we have the remove the ability to set context field while storing on-chain
