### ISSUE TITLE
Setting up monitoring and logging and alerting

### ISSUE THREAD

**Issue by Vishwas1** [hypersign-protocol/hid-node#242]
- https://docs.tendermint.com/master/nodes/metrics.html
- https://kb.certus.one/monitoring.html
- https://medium.com/cypher-core/cosmos-how-to-set-up-your-own-network-monitoring-dashboard-fe49c63a8271
- https://blog.solarlabs.ee/cosmos-how-to-monitoring-your-validator-892a46298722  - important blog to read
- [x] Setup a single ndoe network
- [x] Setup prometheus
- [x] Setup grafana
- [ ] Setup Logging
- [ ] Setup Alerting

**Comment by arnabghose997** [comment]
List of metrics:
https://docs.tendermint.com/v0.35/nodes/metrics.html#metrics

**Comment by arnabghose997** [comment]
## Grafana Related Notes

- Prometheus, by default, runs on port 9090. While setting up Prometheus as the Data Source in Grafana, make sure to provide 9090 port address in the server URL.

**Comment by arnabghose997** [comment]
## Promethus Related Notes

- Reference for Prometheus configs for Cosmos SDK: https://github.com/zhangyelong/cosmos-dashboard

**Comment by arnabghose997** [comment]
## Logs

https://www.baeldung.com/linux/redirect-systemd-output-to-file - Directing systemd service output to a log file

**Comment by arnabghose997** [comment]
https://medium.com/the-interchain-foundation/announcing-panic-a-blockchain-infrastructure-monitoring-solution-5f7bfce6c786

**Comment by arnabghose997** [comment]
PANIC - Node Monitoring Framework

https://medium.com/the-interchain-foundation/announcing-panic-a-blockchain-infrastructure-monitoring-solution-5f7bfce6c786
