### ISSUE TITLE
Researching on network architecture for validator node.

### ISSUE THREAD

**Issue by Vishwas1** [hypersign-protocol/hid-node#243]
- [Understandin concept of validator - tendermint doc](https://docs.tendermint.com/master/nodes/validators.html)
- [Important resources for validators](https://forum.cosmos.network/t/validators-cosmos-tendermint-guides-tools-learning-resources/2246)
- [sentry-validator setup architecture](https://forum.cosmos.network/t/sentry-node-architecture-overview/454/36)
- [Concepts of tendermint for settup nodes in  prod](https://github.com/tendermint/tendermint/tree/d542d2c3945116697f60451e6a407082c41c3cc9/docs/tendermint-core)
- [Running v7-Theta Public Testnet](https://github.com/cosmos/testnets/tree/master/v7-theta/public-testnet)
- [Comos-hub test net](https://github.com/cosmos/testnets)
- [Running a validator in Gaia](https://github.com/cosmos/gaia/blob/main/docs/validators/validator-setup.md)
- [Testnet setup  asmodat](https://github.com/asmodat/KB/tree/master/Cosmos/Testnet)
- [The 2019 Chorus Validator Architecture  ](https://gdoc.pub/doc/e/2PACX-1vQXb1kd0zqYT8K4B4XYb-lrlfRIuPDXsgiTjj94gDOjw3ezEUAtjvxR8yfbKJypmioKeGRrhkLCtZog)

**Comment by Vishwas1** [comment]
<img width="1093" alt="image" src="https://user-images.githubusercontent.com/15328561/183825319-412b150b-4d88-4744-91c0-318a453a8cc5.png">

**Comment by Vishwas1** [comment]
![photo_2022-08-10 10 57 53](https://user-images.githubusercontent.com/15328561/183825972-e801f7d7-3d01-4cf4-9b42-a189e2339c13.jpeg)


> Btw, it’s unrelated to this weird behavior but: 
On the graph, may I know why you chose to have the sentry nodes “know” the validator node and not the otherway around? Wouldn’t be safer to have the validator node have the sentry nodes’s id in its persistent peer list?

> Ideally yes, this is how it should be but there are two ascpects which I want to highlight here. 1) Even though sentry nodes knows the id of Validator node but it also added its id in private_peer_list -  meaning sentry node will not expose any information about validator node in public. 2) say we set the sentry. node with AutoScaling, in the event of DDos attack, more sentry new nodes will be spun,  and if sentry nodes id are set in peer list of vlaidtors then in that case, validators nodes config need to be updated with ids of new sentry nodes and the node need to be restarted, and that has to be done automaically (I am not sure how can this be possible)

**Comment by Vishwas1** [comment]
<img width="1604" alt="image" src="https://user-images.githubusercontent.com/15328561/183850054-055b63cd-9734-483c-8bd1-1410ca2dfe11.png">
https://www.slideshare.net/MichaelNg59/introducing-new-proofofstake-based-networks-why-your-network-participation-matters

**Comment by Vishwas1** [comment]
- [[A look inside iqlusion’s Cosmos Hub Validator architecture](https://iqlusion.blog/a-look-inside-our-validator-architecture)](https://iqlusion.blog/a-look-inside-our-validator-architecture)
- https://medium.com/chorus-one
- [Chorus validator architecture](https://gdoc.pub/doc/e/2PACX-1vQXb1kd0zqYT8K4B4XYb-lrlfRIuPDXsgiTjj94gDOjw3ezEUAtjvxR8yfbKJypmioKeGRrhkLCtZog)
- [Full Disclosure: Figment’s Cosmos Validator Infrastructure](https://medium.com/figment/full-disclosure-figments-cosmos-validator-infrastructure-3bc707283967)

**Comment by Vishwas1** [comment]
![image](https://user-images.githubusercontent.com/15328561/190964234-49dda2ae-58c8-4b02-b37d-d19142e5d9c4.png)

**Comment by Pratap2018** [comment]
https://github.com/hypersign-protocol/hid-node/issues/245
