### ISSUE TITLE
HSM for signing

### ISSUE THREAD

**Issue by Vishwas1** [hypersign-protocol/hid-node#244]
- https://kb.certus.one/hsm.html
- https://github.com/iqlusioninc/tmkms
- https://cpl.thalesgroup.com/encryption/hardware-security-modules

> Fortunately, the [Interchain Foundation](https://interchain.io/) has worked with a team to build a key management server for validators. You can find documentation on how to use it [here](https://github.com/iqlusioninc/tmkms), it is used extensively in production. You are not limited to using this tool, there are also [HSMs](https://safenet.gemalto.com/data-encryption/hardware-security-modules-hsms/), there is not a recommended HSM.

> Currently Tendermint uses [Ed25519](https://ed25519.cr.yp.to/) keys which are widely supported across the security sector and HSMs.

**Comment by arnabghose997** [comment]
https://github.com/persistenceOne/persistenceCore/blob/master/docs/resources/Ledger.md#install-the-persistence-ledger-application
