### ISSUE TITLE
Setting sentry node with validator node to mitigate dDos attack

### ISSUE THREAD

**Issue by Vishwas1** [hypersign-protocol/hid-node#245]
https://forum.cosmos.network/t/sentry-node-architecture-overview/454

**Comment by Pratap2018** [comment]
## Simple Sentry Node Architecture 
![Simpe Sentry Architecture](https://user-images.githubusercontent.com/39677673/190964129-dcbd266a-4f8d-46b8-89cc-c947f1bb3364.png)


## Private Sentry Node 

![Private Sentry](https://user-images.githubusercontent.com/39677673/190964168-29457a7f-75db-48d7-ace4-e801b6978790.png)



## Relay Architecture
 
![Relay](https://user-images.githubusercontent.com/39677673/190964248-e3e3c70f-640e-4dcf-b2b8-07ec0b046cf7.png)

**Comment by Pratap2018** [comment]
## Our Architecture 


![image](https://user-images.githubusercontent.com/39677673/190964409-01761670-c856-48e9-806c-473224a33a7d.png)

**Comment by Pratap2018** [comment]
# Modified Architecture 

![Jagrat-Auto-scale drawio](https://user-images.githubusercontent.com/39677673/191265606-28a02f8f-4064-4c9f-aa2b-5976cd74f1a6.png)

**Comment by Pratap2018** [comment]
# Zoomed 
![Jagrat-Auto-scale drawio (1)](https://user-images.githubusercontent.com/39677673/191265912-17a846ce-8d8e-4d30-8c88-eb665162cf78.png)

**Comment by Pratap2018** [comment]
## Discussion on DevOps (Sentry and Validator)

https://github.com/hypersign-protocol/hypersign-knowledge-hub/discussions/21
