### ISSUE TITLE
Understand configuration (config.toml) of cosmos sdk

### ISSUE THREAD

**Issue by Pratap2018** [hypersign-protocol/hid-node#248]
Understand all params of config.toml file 

https://docs.tendermint.com/master/nodes/configuration.html

**Comment by arnabghose997** [comment]
### `config.toml` 

**proxy_app** - 

**moniker** - Name of the node

**fast_sync** - If this node is many blocks behind the tip of the chain, FastSync
 allows them to catchup quickly by downloading blocks in parallel and verifying their commits

**db_backend** - Backend Database system to store blockchain data. By default, LevelDB is used (https://github.com/syndtr/goleveldb)

**db_data** - File Directory where the blockchain data is stored.

**log_level** - It specifies the logging level. It takes values : trace, debug, info, warn, error, fatal, panic

**log_format** - Output format of Logs. Values: "plain" and "json"

**genesis_file** - Path for genesis file

**priv_validator_key_file** - Path to file which holds the private key for a validator used in consensus protocol. A validator usually have two key pairs: one for consensus (prefix `hidvalconspub`) and another for its validator account (prefix `hidvaloper`). 

**priv_validator_state_file** - Path to file containing the last sign state of a validator. Example
```
{
  "height": "260",
  "round": 0,
  "step": 3,
  "signature": "dxG5zs3+rPBnMLR43focHqUOnJC+MgKBPufENQ2g8+GgASZkzvSd6KZ9wEnhBQuDOJTcMXSAo0epycpMiI4gCw==",
  "signbytes": "6B080211040100000000000022480A2026673C95BD4D5970CFA66481F4C1081551CCB993099044714F8898685856C40D1224080112202C9F2C34BD0F9BF1737B0B60411FD579E7192EB9C6DDB03025C5B9EF6A4BD88E2A0B08B5C7C8970610E9B7F47332076869646E6F6465"
}
```

**priv_validator_laddr** - 

**node_key_file** - Path to file containing the private key for node authentication. This private key belongs to the key pair of the validator's account (prefix `hidvaloper`)

**abci** -  Mechanism to connect to the ABCI application: socket | grpc (TODO)

**filter_peers** -

**Comment by Pratap2018** [comment]
## [p2p] Settings


  - laddr = "tcp://0.0.0.0:26656" 
   Address to listen for incoming connections (this should be 0.0.0.0 so that it can bind to all the network interfaces )
---
#####      For local or private networks this should be left  blank
 - external-address = <Public IP address > 
 This address will be used by the other nodes to find this node (<public_ip: p2p_port>)
---
##### Deprecated in Tendermint v0.35
- seeds = is a list of comma-separated seed nodes that you will connect upon a start and ask for peers. 
- A seed node is a node that does not participate in consensus but only helps propagate peers to nodes in the networks Deprecated, and replaced by bootstrap peers

---
- persistent-peers = is a list of comma-separated peers that you will always be connected to. If you're already connected to the maximum number of peers, persistent peers will not be added to the address book.
--- 
##### Port mapping and port forwarding are synonyms. In its simplified form, it is a method of sending the router’s incoming traffic to a client behind a shared IP. Many protocols address this issue. In truth, only some of them caught traction in creating the dynamic and on-demand port mapping. The most widespread protocol used for port mapping is UPnP. It is an acronym for Universal Plug and Play (although it serves a much greater purpose than mere port mapping).

#### In a simpler language if we are running a node inside a windows subsystem (eg. WSL ) or virtual box then this parameter should be true.

- upnp = false 
---
- addr_book_file = "config\\addrbook.json" 
###### It stores the connected peers list
---
##### Set true for strict address routability rules
##### Set false for private or local networks
- addr_book_strict = false
---

---

**Comment by arnabghose997** [comment]
## Notes

- Those Nodes which are set as Private Peer IDs will not be populated in the seed node's address book.

**Comment by arnabghose997** [comment]
## Sentry Node

Following are the parameters that need to be changed  in `config.toml`:

**Base Config**

mode = "full"

**[p2p]**

persistent_peers = It should contain the seed id of validator node
addr_book_strict = `false`
pex = `true`
seed_mode = `true`
private_peer_id = It should contain the seed id of the validator node.  In this way, no node (connected to sentry node) will be able to figure out about the validator node.

**Comment by arnabghose997** [comment]
## Validator Node Config

Following are the paramters that need to be changed in `config.toml`:

**Base Config**

mode = "validator"

**[p2p]**

addr_book_str = `true` (If its set to true, non routable IPs won't be added in address book)

**Comment by arnabghose997** [comment]
Config.toml Reference - https://github.com/cheqd/infra/blob/main/ansible/roles/cheqd/templates/config.toml.j2

**Comment by Vishwas1** [comment]
## Other setting

- [create-empty-blocks = true ](https://docs.tendermint.com/master/nodes/configuration.html#create-empty-blocks-true)
- [New paramaters for P2P which got added](https://docs.tendermint.com/master/nodes/configuration.html#new-parameters) like `queue-type`, `bootstrap-peers`, `max-connections`
- Depreceated Params: `max-num-inbound-peers`, `max-num-outbound-peers`, `unconditional-peer-ids`, `seeds`

**Comment by arnabghose997** [comment]
**Can we set the maximum size of ttransaction?**

Yes, we can. The param `max_tx_bytes` under `[mempool]` allows us to do.

We need to keep in mind that, not any size of did doc can be created on our network.  We also need to find whatswould be the optimal size that we should support. (for SSI realted txs)
