### ISSUE TITLE
Hardware requirement to run nodes

### ISSUE THREAD

**Issue by Vishwas1** [hypersign-protocol/hid-node#249]
Please add recommended hardware requirement for running nodes in cosmos.  Also mentioned  reference links

**Comment by arnabghose997** [comment]
AssetMantle - https://github.com/AssetMantle/genesisTransactions/tree/main/test-mantle-1

**Comment by arnabghose997** [comment]
Cheqd:

![image](https://user-images.githubusercontent.com/32813269/184191597-8909f8d7-cca0-43f0-b7ba-ac32ca5bc64e.png)
