### ISSUE TITLE
Technical Questions related to hid test net launch

### ISSUE THREAD

**Issue by Vishwas1** [hypersign-protocol/hid-node#250]

**Comment by arnabghose997** [comment]
1. Should `minimum-gas-price` and `minimum-stake` be set by validator’s own choice, or should be defined inside tendermint consensus?
2. Will the rewards of validator be store in his validator address (`hidvaloper`) or normal wallet address (`hid)`
3. What is really meant by peer list?
4. `add-genesis-account` - what should be right amount to be added here? or is it arbotraty?
5. Role of voting power in consensus mechanism? Does stopping node with higher voting power stops the consensus
