### ISSUE TITLE
Research Testing Framework of different projects

### ISSUE THREAD

**Issue by Pratap2018** [hypersign-protocol/hid-node#254]
#### Blockchain-Related Testing
- [x] Staking
- [x] scenario of jailing 
- [ ] scenario of byzantine 
- [x] scenario of delegation
- [x] scenario slashing 
- [x] IBC
- [x] Basic Stress Test

**Comment by arnabghose997** [comment]
QA Testing framework from Cosmos SDK: https://github.com/cosmos/qa-integration

**Comment by arnabghose997** [comment]
### Observations:

- Cosmos Hub: They have written tests in golang, and various scenarios are tested related to blockchain
- Cheqd
  -  They haven't written test in both Bash and Python3
  - They are testing scenarios such as:
    - IBC Token transfer between Osmosis and Cheqd Locally using `hermes` relayer
    - Running full nodes and promoting it to validator and asserting the process
    - Chain Upgrade
    - Cosmos Keys related operations

**Comment by arnabghose997** [comment]
Assertion Golang Package: https://github.com/stretchr/testify

**Comment by arnabghose997** [comment]
## Test Scenarios:

### Validator

1. Addition of a full node and then promoting it to a validator node
2. Checking if a validator is receiving rewards
3. Switching off one of the validators for blocks beyond the threshold block height, to check if the validator is jailed.
4. Check for double singing a.k.a, byzantine behaviour

**Comment by arnabghose997** [comment]
Reference for simulating byzantine node: https://gist.github.com/cwgoes/3ab18585a72966bb9e68e8a9428a28b8

**Comment by arnabghose997** [comment]
Governance:

Node Upgrade: https://github.com/hypersign-protocol/hid-node/issues/155#issuecomment-1220542397

Genesis Param change:


Community Proposal Spend:

**Comment by arnabghose997** [comment]
Stress Testing Ref: https://github.com/DaevMithran/tendermint-load-test
