### ISSUE TITLE
Implment Other concepts of SSI like Claim Definition & Revocation Registry

### ISSUE THREAD

**Issue by Vishwas1** [hypersign-protocol/hid-node#26]
Apart from DID and Schema, I found these in Hyperldeger Indy project. 

- [CLAIM_DEF](https://hyperledger-indy.readthedocs.io/projects/node/en/latest/transactions.html#claim-def)
- [REVOC_REG_DEF](https://hyperledger-indy.readthedocs.io/projects/node/en/latest/transactions.html#revoc-reg-def)

But none of these I could found in w3c spec. So we need to see how other projects are doing like Ceramic and Ontology etc.

**Comment by arnabghose997** [comment]
Closing this issue as its handled in https://github.com/hypersign-protocol/hid-node/issues/151
