### ISSUE TITLE
Implement verify DIDdoc proof on chain

### ISSUE THREAD

**Issue by Vishwas1** [hypersign-protocol/hid-node#35]
>  A smart contract or application specific module should call this method at the time of didAuth

Similar to this functionality, implement verify didDoc proof on chain
https://github.com/hypersign-protocol/hs-ssi-sdk/blob/fa6818a41a14748bb21e65cc90ef39a445bd52e3/src/did.ts#L216

**Comment by arnabghose997** [comment]
DidDoc signature verification is perfomed on on-chain
