### ISSUE TITLE
Implement Verifiable Presentation

### ISSUE THREAD

**Issue by Vishwas1** [hypersign-protocol/hid-node#36]
> The smart contract should be able to call this method to verify verifiable presentation sent by user

Similar to this functionality 

- https://github.com/hypersign-protocol/hs-ssi-sdk/blob/fa6818a41a14748bb21e65cc90ef39a445bd52e3/src/credential.ts#L223 
- https://github.com/hypersign-protocol/hs-ssi-sdk/blob/fa6818a41a14748bb21e65cc90ef39a445bd52e3/src/credential.ts#L184

**Comment by arnabghose997** [comment]
Closing this issue as it is handled in  https://github.com/hypersign-protocol/hs-ssi-sdk/issues/17
