### ISSUE TITLE
Implement DID meta data with didDoc; did versioning

### ISSUE THREAD

**Issue by Vishwas1** [hypersign-protocol/hid-node#42]
- https://www.w3.org/TR/did-core/#metadata-structure 
- https://w3c.github.io/did-spec-registries/#did-document-metadata
- this is how cheqd have done https://docs.cheqd.io/node/architecture/adr-list/adr-002-cheqd-did-method#diddoc-metadata

```
{
  "created": "2020-12-20T19:17:47Z",
  "updated": "2020-12-20T19:19:47Z",
  "deactivated": false,
  "versionId": "1B3B00849B4D50E8FCCF50193E35FD6CA5FD4686ED6AD8F847AC8C5E466CFD3E",
}
```

**Comment by arnabghose997** [comment]
The PR #77 has been merged with the branch [v0.0.3](https://github.com/hypersign-protocol/hid-node/tree/v0.0.3)
