### ISSUE TITLE
Test with different secruity suites; use `context` based on signature type

### ISSUE THREAD

**Issue by Vishwas1** [hypersign-protocol/hid-node#51]
1. Context `https://www.w3.org/ns/did/v1` is common in all didDoc. 
2. Use Context `https://w3id.org/security/suites/ed25519-2020/v1` if signature type is `Ed25519VerificationKey2020` [Example](https://www.w3.org/TR/did-core/#example-30-did-document-with-1-verification-method-type) 
    ```
      {
        "id": "did:example:123#z6Mkw94ByR26zMSkNdCUi6FNRsWnc2DFEeDXyBGJ5KTzSWyi",
        "type": "Ed25519VerificationKey2020", // external (property value)
        "controller": "did:example:123",
        "publicKeyMultibase": "zHgo9PAmfeoxHG8Mn2XHXamxnnSwPpkyBHAMNF3VyXJCL"
      }
    ```
3. Use context `https://w3id.org/security/suites/jws-2020/v1` if signature type is `JsonWebKey2020`. [Example](https://www.w3.org/TR/did-core/#example-31-did-document-with-many-different-key-types)
    ```{
          "id": "did:example:123#key-0",
          "type": "JsonWebKey2020",
          "controller": "did:example:123",
          "publicKeyJwk": {
            "kty": "OKP", // external (property name)
            "crv": "Ed25519", // external (property name)
            "x": "VCpo2LMLhn6iWku8MKvSLg2ZAoC-nlOyPVQaO3FxVeQ" // external (property name)
          }
        }
    ```
4. List of all supported security suites can be found here https://w3c-ccg.github.io/ld-cryptosuite-registry/

**Comment by arnabghose997** [comment]
The `context` field will be handled in the DID Resolver
