### ISSUE TITLE
Implement `alsoknownas` property in diddoc

### ISSUE THREAD

**Issue by Vishwas1** [hypersign-protocol/hid-node#53]
https://www.w3.org/TR/did-core/#also-known-as

> A [DID subject](https://www.w3.org/TR/did-core/#dfn-did-subjects) can have multiple identifiers for different purposes, or at different times. The assertion that two or more [DIDs](https://www.w3.org/TR/did-core/#dfn-decentralized-identifiers) (or other types of [URI](https://www.w3.org/TR/did-core/#dfn-uri)) refer to the same [DID subject](https://www.w3.org/TR/did-core/#dfn-did-subjects) can be made using the [alsoKnownAs](https://www.w3.org/TR/did-core/#dfn-alsoknownas) property

> alsoKnownAs (optional): A list of strings. A DID subject can have multiple identifiers for different purposes, or at different times. The assertion that two or more DIDs refer to the same DID subject can be made using the alsoKnownAs property.

**Comment by Vishwas1** [comment]
We need to come back to see the usage of this property. 


> As we understood that, this property is used for say, "What all DIDs have acccess to this didDoc"? similar to controller.

**Comment by arnabghose997** [comment]
- https://www.w3.org/TR/did-core/#assigning-dids-to-existing-web-resources
