### ISSUE TITLE
Implement `deactivate_did` RPC

### ISSUE THREAD

**Issue by Vishwas1** [hypersign-protocol/hid-node#58]
- https://www.tyronzil.com/CRUD-operations/did-deactivate/
-

**Comment by Vishwas1** [comment]
From w3c spec

> If a DID has been [deactivated](https://www.w3.org/TR/did-core/#method-operations), [DID document](https://www.w3.org/TR/did-core/#dfn-did-documents) metadata MUST include this property with the boolean value true. If a DID has not been deactivated, this property is OPTIONAL, but if included, MUST have the boolean value false.

> a [DID controller](https://www.w3.org/TR/did-core/#dfn-did-controllers) can deactivate a [DID](https://www.w3.org/TR/did-core/#dfn-decentralized-identifiers) or state that deactivation is not possible.

- Deactivates DID by setting DID metadata:`deactivate == true` & `didDoc == null / {}`
- After deactivation,  the DID is not useful anymore. Resolving DID should return err `DID_Deactivate` err.

steps:

1.

**Comment by arnabghose997** [comment]
Discussion of treating deactivated DIDs : https://github.com/w3c-ccg/did-resolution/issues/5
