### ISSUE TITLE
Cross check all `did-doc` data model from the w3c spec

### ISSUE THREAD

**Issue by Vishwas1** [hypersign-protocol/hid-node#59]
https://www.w3.org/TR/did-core/#did-document-properties
![image](https://user-images.githubusercontent.com/15328561/154021785-29cdec25-d4a2-407b-b8d3-56f85dbb00f0.png)

1. id: https://www.w3.org/TR/did-core/#did-subject
2. controller:  https://www.w3.org/TR/did-core/#did-controller
3. alsoknownus: https://www.w3.org/TR/did-core/#also-known-as
4. verification method: https://www.w3.org/TR/did-core/#verification-methods
5. authenticaion:  https://www.w3.org/TR/did-core/#authentication
6. assertion:  https://www.w3.org/TR/did-core/#assertion
7. keyagreemetn: https://www.w3.org/TR/did-core/#key-agreement
8. capability invocation: https://www.w3.org/TR/did-core/#capability-invocation
9. capability delegation : https://www.w3.org/TR/did-core/#capability-delegation
10. services : https://www.w3.org/TR/did-core/#services

**Comment by arnabghose997** [comment]
List of DID Doc examples: https://www.w3.org/TR/did-core/#examples

**Comment by arnabghose997** [comment]
The fields have been implemented. However, there are issues with label `need-to-come-back` that needs to be reflect upon later.
