### ISSUE TITLE
Cross check `verification` method data model from w3c spec

### ISSUE THREAD

**Issue by Vishwas1** [hypersign-protocol/hid-node#60]
https://www.w3.org/TR/did-core/#verification-method-properties

![image](https://user-images.githubusercontent.com/15328561/154022173-a46d43db-26b0-4931-abc0-5dad9141d9a4.png)

**Comment by arnabghose997** [comment]
#### Linked Issues:

- https://github.com/hypersign-protocol/hid-node/issues/48
