### ISSUE TITLE
Cross check `serviceEp` data model from the w3c spec

### ISSUE THREAD

**Issue by Vishwas1** [hypersign-protocol/hid-node#61]
https://www.w3.org/TR/did-core/#service-properties

![image](https://user-images.githubusercontent.com/15328561/154022388-fccbb220-88d5-4e52-951c-bb58d4b40e8c.png)

- The value `linkedDomain` come from [here](https://identity.foundation/.well-known/did-configuration/v1/)
- There are other types of services like `DomainLinkageCredential`, `orgin`, `linked_dids` etc. 
- https://identity.foundation/.well-known/did-configuration/v1/

**Comment by arnabghose997** [comment]
Implementation done in #50
