### ISSUE TITLE
Implement DID Resolve

### ISSUE THREAD

**Issue by arnabghose997** [hypersign-protocol/hid-node#82]
The `query_did` rPC need to implemented based on the spec. See the spec to understand how did resolution should happen 

https://www.w3.org/TR/did-core/#did-resolution

- https://w3c-ccg.github.io/did-resolution/#resolving

**Comment by Vishwas1** [comment]
Source: https://www.w3.org/TR/did-core/#did-resolution

![image](https://user-images.githubusercontent.com/32813269/155332063-bc3f1fea-f439-4fdd-b924-7ae02837d766.png)

### Narrative Description: https://www.w3.org/TR/did-core/#resolve-resolverepresentation-longdesc

**Comment by Vishwas1** [comment]
We only support JSON LD representation for now.

**Comment by arnabghose997** [comment]
```
resolve ( did, resolutionOptions )
     -> ( didResolutionMetadata, didDocument, didDocumentMetadata )
```

**Comment by Vishwas1** [comment]
```

/// Fetch all did with limit

method: GET
path: "/hypersign-protocol/hidnode/ssi/did?limit=100"
respo
{
   dids: [],
   count:  10
}


/// Fetch didcount

method: GET
path: "/hypersign-protocol/hidnode/ssi/did?count=true"

--- 
resp
{
   dids: [],
   count:  123
}

/// Fetch specific did

method: GET
path: "/hypersign-protocol/hidnode/ssi/did/{id}"

/// Fetch specific verision of a did

method: GET
path: "/hypersign-protocol/hidnode/ssi/did/{id}?versionId={}"



```
