### ISSUE TITLE
Research on Cosmos's `Gov` module

### ISSUE THREAD

**Issue by Vishwas1** [hypersign-protocol/hid-node#92]
- https://docs.cosmos.network/v0.44/modules/gov/
- [Read goverance of Razor](https://docs.razor.network/docs/whitepaper/intro#3-governance)

**Comment by arnabghose997** [comment]
Articles:

https://www.figment.io/resources/cosmos-governance-and-the-validator

**Comment by arnabghose997** [comment]
## Chain related Param change governance proposal  (Cosmos Version: v0.45.6)

- Config `simapp`
```
simd config keyring-backend test
simd config chain-id test
```

- Genesis Param change proposals are usually written in JSON. We will be changing the `x/slashing` module's param `slash_fraction_downtime`. An important point to note is that, although the param is written in snake case, while mentioning this param in the below JSON, it should be written in Capital Camel Case. Create a JSON file and add the below contents:
```json
{
  "title": "Parameter changes for validator downtime",
  "description": "This is just a test description",
  "changes": [
    {
      "subspace": "slashing",
      "key": "SlashFractionDowntime",
      "value": "0.310000000000000000"
    }
  ],
  "deposit": "5120000stake"
}
```
The deposit amount above should be greater than or equal to minimum gov proposal deposit.

- Submit the proposal
```
simd tx gov submit-proposal param-change <path-to-json> --from validator --broadcast-mode block -y
```

- Query the proposal
```
simd q gov proposal <proposal-id> 
```

- Vote `yes` for the proposal
```
simd tx gov vote <proposal-id> yes --from validator  --broadcast-mode block -y
```

- Once the voting period ends and the proposal passes, check the param change
```
simd q slashing params
```

**Comment by arnabghose997** [comment]
### Community Spend Proposal (Cosmos Version: v0.45.6)

This proposal is about using the community pool to award grants.

Proposing this is like that of proposing param change, except from the JSON file structure, which is something like following:
```json
{
    "title": "Community Pool Spend - 1",
    "description": "This is the summary of the key information about this proposal. Include the URL to a PDF version of your full proposal.",
    "recipient": "<recipient-wallet-address>",
    "amount": "684342667stake",
    "deposit": "10000000stake"
}
```
`amount` field referes to the amount of tokens a `recipient` is supposed to recieve

- Submit the proposal
```
simd tx gov submit-proposal community-pool-spend <path-to-proposal-json-file> --from validator --broadcast-mode block
```

- Query the proposal
```
simd q gov proposal <proposal-id> 
```

- Vote `yes` for the proposal
```
simd tx gov vote <proposal-id> yes --from validator  --broadcast-mode block -y
```

- Once the voting period ends and the proposal passes, check the balance of the recipient
```
simd q bank balances <recipient-wallet-address>
```
