### ISSUE TITLE
Research on Cosmos's `mint` module

### ISSUE THREAD

**Issue by Vishwas1** [hypersign-protocol/hid-node#93]
https://docs.cosmos.network/v0.44/modules/mint/01_concepts.html

**Comment by arnabghose997** [comment]
- The `mint` module only has the Query Service. It lists the inflation, annual_provisions (total_coin_supply * inflation) and related params as following:

```sh
$ hid-noded query mint inflation
0.100002000000000000

$ hid-noded query mint annual-provisions
10000419388.387680000000000000

$ hid-noded query mint params
blocks_per_year: "6311520"
goal_bonded: "0.078002000000000000"
inflation_max: "0.100002000000000000"
inflation_min: "0.088002000000000000"
inflation_rate_change: "0.999000000000000000"
mint_denom: uhid
```

- The params (last command's output) that is seen above are defined at the time of genesis, where we define these params in the genesis file.

**Comment by arnabghose997** [comment]
- https://github.com/gavinly/CosmosParametersWiki/blob/master/Mint.md
